language: minimal
services:
- docker
script:
- docker build -t "$REPO":${TRAVIS_TAG:-latest} .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [[ ( "$TRAVIS_BRANCH" == "master" ) || ( -n "$TRAVIS_TAG" ) ]]; then docker push
  "$REPO":${TRAVIS_TAG:-latest}; fi
env:
  global:
  - REPO=osirrc2019/entityretrieval
  - secure: c1NWBKks9qYiJYoAAimbqPLvvTWkg0GzGQzbb+loyQG9FInKwETh0zxGq8rvumhh6/RywRadpbnDshG2jSeL4tBNLCP4HBC0Wg7iLw36H49F/XZgZEUkx0ChFINsYXSl+7qpt5hyXDh4VblidFyBhRXLP9yf0YD5cyDl1cIL98VQjiUJsypYmqX7P/NMuM9kw0wOogC+TlF+acF0R4KcUSTmHpl3k7jd1eVT8Z7Tg/gG4LdilqJPFlB8M8ic7V6EcjXMUc1r1ADBX9HM1MR0N48BcpeGf9jTE0UbBtBs6/Wve2/WWJVjbTk0fLhpBuwuZ+vlRSAJosnacICKN2A3u5ltLa5WzTKqWy3kDr7CIY7vIGHKGvleAXUV2M+kxsfhICtOnMSvBKOfpat8LZmc75Y5m5xpXbn2FGEfZqQYUUXf+2ZDx2xz+R+NPFBHVh1DKfftMgzdfjJ7psCG/vp+xXB0yexnOVe7m5abO8zqFh69avAgQ/liG0R2XXJV7qd5eiwL1b9jgDyXBgpKLRy45pHGjgRyYpMEAMQauSshFZ6zykFbQDiVObNsYbhcxFbzhTW27Hn78Non4QZZ3VzeiRO9uFODl43h8/YUVuXzefTa/73i6IhJoBWiU0XZbU0yG+dM//015qsz5u+L0zbyqe08zillw8SVZPqkPTQxrFY=
  - secure: YZ9MgYorRzLuM+OGy6r+W1WVhHSbFZT+k8X+iGazR/KUNxJ4BQFtGw9HhIB3/2+HIh5YNTyi5AU6v9URNk3OwdAL+0NQMYa/qWZH9QSiMWA184nSfw4VcUoL5czdjWaNbb5tufd443b0ouI/2ua7ey3oaamMj2nAKMZrDWReJQmFOBjG9idJ+hQ+VKfliKRaWS2tHJabVikChztGP2hIfiDvnWooGVnMPExc9+IEuql6B49zosk0r17WPTDKKpt+6BhYc53I4w/f4/rjABuFKzBwKozpOqof7rU7mLiPlSsPi9vmDfJF8BI2Rjti1NypIk0wy9EWcOhyWKNjvasGzQwseutbYVaOvoQliwvVUPoCr9DfCon1wdSXM/cNeS5BahPx8q9BH3qC5B5FhP1l58KJLYW265cwibewYvmXILG4l/rbCnlcJ/enMRsvOKYFjZrKN9d7DUZAw5r1K1k/vlTnIEuNLGG5usvNYuw909lOfJNC9kRJOyknUOOMSX/pYJ37lbannNVicCLUZ6Yp9hUP209Lh/Qr9beaqXNl3HXA3jRxT9eL8eivKF89OLCHii2TH1X7Xo+24s21AKa1LSMVBNKNXOTZ2L62SBJ9GLnC40O3sdX3jiAUp4EBhWG8nmqG5ed9jjiXxkvTusu16YkBqqiNbZbN+7VOm44WFww=
