#!/usr/bin/env python3
import os
import argparse
import json
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the json input")
args, unknown = parser.parse_known_args()

topic_path = args.json["topic"]["path"]
mod = args.json["opts"]["model"]
threshold=(args.json["opts"]["threshold"])    
annotation_file= (args.json["opts"]["annotation"])
nfields=(args.json["opts"]["nfields"])
    
print(mod,topic_path,threshold,nfields,annotation_file)
os.chdir("//elr_files//EntityLinkingRetrieval-ELR-master")
subprocess.run("python -m nordlys.elr.retrieval_elr {} -q {} -t {} -n {} -a{} ".format(mod,topic_path,threshold,nfields,annotation_file),shell=True)






